apiVersion: v1
kind: ServiceAccount
metadata:
  name: sshd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sshd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sshd
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sshd-authorized-keys
  namespace: kube-system
data:
  # TODO: add your keys here
  authorized_keys: |
    ecdsa-sha2-nistp256 AAAA...
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sshd
  namespace: kube-system
  labels:
    app: sshd
spec:
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      serviceAccountName: sshd
      automountServiceAccountToken: true
      enableServiceLinks: false
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: sshd
          image: ghcr.io/mologie/alpine-debug:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host
              name: host
              readOnly: true
            - mountPath: /root/.ssh
              name: sshd-authorized-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ecdsa_key
              subPath: ssh_host_ecdsa_key
              name: sshd-host-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ecdsa_key.pub
              subPath: ssh_host_ecdsa_key.pub
              name: sshd-host-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: ssh_host_ed25519_key
              name: sshd-host-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
              subPath: ssh_host_ed25519_key.pub
              name: sshd-host-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key
              subPath: ssh_host_rsa_key
              name: sshd-host-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key.pub
              subPath: ssh_host_rsa_key.pub
              name: sshd-host-keys
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      volumes:
        - name: host
          hostPath:
            path: /
        - name: sshd-authorized-keys
          configMap:
            name: sshd-authorized-keys
            defaultMode: 0644
        - name: sshd-host-keys
          secret:
            secretName: sshd-host-keys
            defaultMode: 0400
